// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ClassInfo;
@class ClassInfoBuilder;



@interface ClassRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ClassInfo_project @"project"
#define ClassInfo_price @"price"
#define ClassInfo_teacher @"teacher"
#define ClassInfo_id @"id"
@interface ClassInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPrice_:1;
  BOOL hasId_:1;
  BOOL hasProject_:1;
  BOOL hasTeacher_:1;
  SInt32 price;
  SInt32 id;
  NSString* project;
  NSString* teacher;
}
- (BOOL) hasProject;
- (BOOL) hasPrice;
- (BOOL) hasTeacher;
- (BOOL) hasId;
@property (readonly, strong) NSString* project;
@property (readonly) SInt32 price;
@property (readonly, strong) NSString* teacher;
@property (readonly) SInt32 id;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ClassInfoBuilder*) builder;
+ (ClassInfoBuilder*) builder;
+ (ClassInfoBuilder*) builderWithPrototype:(ClassInfo*) prototype;
- (ClassInfoBuilder*) toBuilder;

+ (ClassInfo*) parseFromData:(NSData*) data;
+ (ClassInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClassInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ClassInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ClassInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ClassInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ClassInfoBuilder : PBGeneratedMessageBuilder {
@private
  ClassInfo* resultClassInfo;
}

- (ClassInfo*) defaultInstance;

- (ClassInfoBuilder*) clear;
- (ClassInfoBuilder*) clone;

- (ClassInfo*) build;
- (ClassInfo*) buildPartial;

- (ClassInfoBuilder*) mergeFrom:(ClassInfo*) other;
- (ClassInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ClassInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProject;
- (NSString*) project;
- (ClassInfoBuilder*) setProject:(NSString*) value;
- (ClassInfoBuilder*) clearProject;

- (BOOL) hasPrice;
- (SInt32) price;
- (ClassInfoBuilder*) setPrice:(SInt32) value;
- (ClassInfoBuilder*) clearPrice;

- (BOOL) hasTeacher;
- (NSString*) teacher;
- (ClassInfoBuilder*) setTeacher:(NSString*) value;
- (ClassInfoBuilder*) clearTeacher;

- (BOOL) hasId;
- (SInt32) id;
- (ClassInfoBuilder*) setId:(SInt32) value;
- (ClassInfoBuilder*) clearId;
@end


// @@protoc_insertion_point(global_scope)
